# Generated by Django 4.0.4 on 2022-05-24 04:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_post_customuser_dob_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, upload_to='facebook/images/user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default=None, upload_to='facebook/images/post/%Y/%m'),
        ),
    ]
